services:
  live_server:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: prod
    image: ${DOCKERHUB_USERNAME:-daheepk}/live_server:latest
    ports:
      - "80:80"
      - "443:443"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_ENV: prod
      SPRING_DATASOURCE_DB1_PROD_JDBC_URL: ${APPLICATION_SPRING_DATASOURCE_DB1_PROD_JDBC_URL}
      SPRING_DATASOURCE_DB2_PROD_JDBC_URL: ${APPLICATION_SPRING_DATASOURCE_DB2_PROD_JDBC_URL}
      KAKAO_CLIENT_ID: ${APPLICATION_KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${APPLICATION_KAKAO_PROD_REDIRECT_URI}
      SPRING_DATASOURCE_DB1_USERNAME: ${APPLICATION_SPRING_DATASOURCE_DB1_USERNAME}
      SPRING_DATASOURCE_DB1_PASSWORD: ${APPLICATION_SPRING_DATASOURCE_DB1_PASSWORD}
      SPRING_DATASOURCE_DB2_USERNAME: ${APPLICATION_SPRING_DATASOURCE_DB2_USERNAME}
      SPRING_DATASOURCE_DB2_PASSWORD: ${APPLICATION_SPRING_DATASOURCE_DB2_PASSWORD}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}