version: '3.8'

services:
  live_server:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: prod
    image: ${DOCKERHUB_USERNAME:-daheepk}/live_server:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_ENV: prod
    env_file:
      - .env