services:
  live_server:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile
    image: daheepk/live_server:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/main/resources/ssl:/app/ssl:ro
    env_file:
      - .env