name: CI/CD using github action & docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  APPLICATION_SPRING_DATASOURCE_DB1_PROD_JDBC_URL: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB1_PROD_JDBC_URL }}
  APPLICATION_SPRING_DATASOURCE_DB2_PROD_JDBC_URL: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB2_PROD_JDBC_URL }}
  APPLICATION_KAKAO_CLIENT_ID: ${{ secrets.APPLICATION_KAKAO_CLIENT_ID }}
  APPLICATION_KAKAO_PROD_REDIRECT_URI: ${{ secrets.APPLICATION_KAKAO_PROD_REDIRECT_URI }}
  APPLICATION_SPRING_DATASOURCE_DB1_USERNAME: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB1_USERNAME }}
  APPLICATION_SPRING_DATASOURCE_DB1_PASSWORD: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB1_PASSWORD }}
  APPLICATION_SPRING_DATASOURCE_DB2_USERNAME: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB2_USERNAME }}
  APPLICATION_SPRING_DATASOURCE_DB2_PASSWORD: ${{ secrets.APPLICATION_SPRING_DATASOURCE_DB2_PASSWORD }}
  SSL_KEY_STORE_PASSWORD: ${{secrets.SSL_KEY_STORE_PASSWORD}}

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker
        run: |
          # Build without environment variables
          docker compose -f docker-compose.yml build --build-arg PROFILES=prod --build-arg ENV=prod
          docker push ${DOCKERHUB_USERNAME}/live_server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend/web/bodam-server || exit
            git pull
            
            # Create env file with filtered environment variables
            printenv | grep -E '^(APPLICATION_|DOCKERHUB_|SSL_)' > .env
            
            # Update container
            sudo docker pull ${DOCKERHUB_USERNAME}/live_server:latest
            sudo docker stop prod || true
            sudo docker rm prod || true
            

            if sudo docker compose -f docker-compose.yml -p live_server up -d --env-file .env; then
              sleep 20
              if sudo docker logs prod | grep -q "Started BodamServerApplication"; then
                echo "Application started successfully"
              else
                echo "Application failed to start. Logs:"
                sudo docker logs prod
                exit 1
              fi
            else
              echo "Docker Compose failed"
              sudo docker compose -f docker-compose.yml logs
              exit 1
            fi