name: CI/CD using github action & docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker
        run: |
          docker compose -f docker-compose.yml build 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest

      - name: Copy .env file to EC2
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env"
          target: "~/backend/web/bodam-server"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend/web/bodam-server || exit
            git fetch origin 
            git reset --hard origin/main
            
            # 기존 컨테이너 정리
            sudo docker stop prod || true
            sudo docker rm prod || true
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest || true
            
            # 새 이미지 pull  
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
            
            # Docker Compose로 재시작 (env-file 사용)  
            if sudo docker compose --env-file .env -f docker-compose.yml -p live_server up -d; then
              sleep 20
              if sudo docker logs prod | grep -q "Started BodamServerApplication"; then 
                echo "Application started successfully"
              else
                echo "Application failed to start. Logs:"
                sudo docker logs prod
                exit 1
              fi
            else 
              echo "Docker Compose failed"
              sudo docker compose -f docker-compose.yml logs 
              exit 1
            fi